class com.google.inject.internal.util.$MapMaker$ComputationExceptionReference extends java.lang.Object implements com.google.inject.internal.util.$MapMaker$ValueReference
{
    final java.lang.Throwable t;

    void <init>(java.lang.Throwable)
    {
        java.lang.Throwable r1;
        com.google.inject.internal.util.$MapMaker$ComputationExceptionReference r0;

        r0 := @this: com.google.inject.internal.util.$MapMaker$ComputationExceptionReference;

        r1 := @parameter0: java.lang.Throwable;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        r0.<com.google.inject.internal.util.$MapMaker$ComputationExceptionReference: java.lang.Throwable t> = r1;

        return;
    }

    public java.lang.Object get()
    {
        com.google.inject.internal.util.$MapMaker$ComputationExceptionReference r0;

        r0 := @this: com.google.inject.internal.util.$MapMaker$ComputationExceptionReference;

        return null;
    }

    public com.google.inject.internal.util.$MapMaker$ValueReference copyFor(com.google.inject.internal.util.$MapMaker$ReferenceEntry)
    {
        com.google.inject.internal.util.$MapMaker$ComputationExceptionReference r0;
        com.google.inject.internal.util.$MapMaker$ReferenceEntry r1;

        r0 := @this: com.google.inject.internal.util.$MapMaker$ComputationExceptionReference;

        r1 := @parameter0: com.google.inject.internal.util.$MapMaker$ReferenceEntry;

        return r0;
    }

    public java.lang.Object waitForValue()
    {
        java.lang.Throwable $r2;
        com.google.inject.internal.util.$MapMaker$ComputationExceptionReference r1;
        com.google.inject.internal.util.$AsynchronousComputationException $r0;

        r1 := @this: com.google.inject.internal.util.$MapMaker$ComputationExceptionReference;

        $r0 = new com.google.inject.internal.util.$AsynchronousComputationException;

        $r2 = r1.<com.google.inject.internal.util.$MapMaker$ComputationExceptionReference: java.lang.Throwable t>;

        specialinvoke $r0.<com.google.inject.internal.util.$AsynchronousComputationException: void <init>(java.lang.Throwable)>($r2);

        throw $r0;
    }
}
