public class org.jdom.JDOMException extends java.lang.Exception
{
    private static final java.lang.String CVS_ID;
    private java.lang.Throwable cause;

    public void <init>()
    {
        org.jdom.JDOMException r0;

        r0 := @this: org.jdom.JDOMException;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String)>("Error occurred in JDOM application.");

        return;
    }

    public void <init>(java.lang.String)
    {
        org.jdom.JDOMException r0;
        java.lang.String r1;

        r0 := @this: org.jdom.JDOMException;

        r1 := @parameter0: java.lang.String;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String)>(r1);

        return;
    }

    public void <init>(java.lang.String, java.lang.Throwable)
    {
        java.lang.Throwable r2;
        org.jdom.JDOMException r0;
        java.lang.String r1;

        r0 := @this: org.jdom.JDOMException;

        r1 := @parameter0: java.lang.String;

        r2 := @parameter1: java.lang.Throwable;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String)>(r1);

        r0.<org.jdom.JDOMException: java.lang.Throwable cause> = r2;

        return;
    }

    public java.lang.Throwable getCause()
    {
        java.lang.Throwable $r1;
        org.jdom.JDOMException r0;

        r0 := @this: org.jdom.JDOMException;

        $r1 = r0.<org.jdom.JDOMException: java.lang.Throwable cause>;

        return $r1;
    }

    public java.lang.String getMessage()
    {
        java.lang.Throwable $r1, r11;
        org.jdom.JDOMException r0;
        java.lang.StringBuffer $r3, $r5, $r6;
        java.lang.String $r2, $r4, $r9, r10, r12;
        boolean $z0, $z1, $z2;
        java.lang.Exception $r8;
        org.xml.sax.SAXException $r7;

        r0 := @this: org.jdom.JDOMException;

        r10 = specialinvoke r0.<java.lang.Throwable: java.lang.String getMessage()>();

        r11 = r0;

        goto label5;

     label1:
        $r2 = virtualinvoke $r1.<java.lang.Throwable: java.lang.String getMessage()>();

        r12 = $r2;

        $z0 = $r1 instanceof org.xml.sax.SAXException;

        if $z0 == 0 goto label2;

        $r7 = (org.xml.sax.SAXException) $r1;

        $r8 = virtualinvoke $r7.<org.xml.sax.SAXException: java.lang.Exception getException()>();

        if $r8 == null goto label2;

        if $r2 == null goto label2;

        $r9 = virtualinvoke $r8.<java.lang.Throwable: java.lang.String getMessage()>();

        $z1 = virtualinvoke $r2.<java.lang.String: boolean equals(java.lang.Object)>($r9);

        if $z1 == 0 goto label2;

        r12 = null;

     label2:
        if r12 == null goto label4;

        if r10 == null goto label3;

        $r3 = new java.lang.StringBuffer;

        $r4 = staticinvoke <java.lang.String: java.lang.String valueOf(java.lang.Object)>(r10);

        specialinvoke $r3.<java.lang.StringBuffer: void <init>(java.lang.String)>($r4);

        $r5 = virtualinvoke $r3.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>(": ");

        $r6 = virtualinvoke $r5.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.String)>(r12);

        r10 = virtualinvoke $r6.<java.lang.StringBuffer: java.lang.String toString()>();

        goto label4;

     label3:
        r10 = r12;

     label4:
        $z2 = $r1 instanceof org.jdom.JDOMException;

        if $z2 != 0 goto label6;

        r11 = $r1;

     label5:
        $r1 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable)>(r11);

        if $r1 != null goto label1;

     label6:
        return r10;
    }

    private static java.lang.Throwable getNestedException(java.lang.Throwable)
    {
        java.lang.Throwable r0, $r1, $r2, $r4, $r6, $r8, $r14;
        java.sql.SQLException $r9, $r10;
        org.jdom.JDOMException $r13;
        boolean $z0, $z1, $z2, $z3, $z4, $z5;
        java.lang.Exception $r12;
        java.rmi.RemoteException $r3;
        java.lang.reflect.InvocationTargetException $r7;
        org.xml.sax.SAXException $r11;
        java.lang.ExceptionInInitializerError $r5;

        r0 := @parameter0: java.lang.Throwable;

        $z0 = r0 instanceof org.jdom.JDOMException;

        if $z0 == 0 goto label1;

        $r13 = (org.jdom.JDOMException) r0;

        $r14 = virtualinvoke $r13.<org.jdom.JDOMException: java.lang.Throwable getCause()>();

        return $r14;

     label1:
        $z1 = r0 instanceof org.xml.sax.SAXException;

        if $z1 == 0 goto label2;

        $r11 = (org.xml.sax.SAXException) r0;

        $r12 = virtualinvoke $r11.<org.xml.sax.SAXException: java.lang.Exception getException()>();

        return $r12;

     label2:
        $z2 = r0 instanceof java.sql.SQLException;

        if $z2 == 0 goto label3;

        $r9 = (java.sql.SQLException) r0;

        $r10 = virtualinvoke $r9.<java.sql.SQLException: java.sql.SQLException getNextException()>();

        return $r10;

     label3:
        $z3 = r0 instanceof java.lang.reflect.InvocationTargetException;

        if $z3 == 0 goto label4;

        $r7 = (java.lang.reflect.InvocationTargetException) r0;

        $r8 = virtualinvoke $r7.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();

        return $r8;

     label4:
        $z4 = r0 instanceof java.lang.ExceptionInInitializerError;

        if $z4 == 0 goto label5;

        $r5 = (java.lang.ExceptionInInitializerError) r0;

        $r6 = virtualinvoke $r5.<java.lang.ExceptionInInitializerError: java.lang.Throwable getException()>();

        return $r6;

     label5:
        $z5 = r0 instanceof java.rmi.RemoteException;

        if $z5 == 0 goto label6;

        $r3 = (java.rmi.RemoteException) r0;

        $r4 = $r3.<java.rmi.RemoteException: java.lang.Throwable detail>;

        return $r4;

     label6:
        $r1 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable,java.lang.String,java.lang.String)>(r0, "javax.naming.NamingException", "getRootCause");

        if $r1 == null goto label7;

        return $r1;

     label7:
        $r2 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable,java.lang.String,java.lang.String)>(r0, "javax.servlet.ServletException", "getRootCause");

        if $r2 == null goto label8;

        return $r2;

     label8:
        return null;
    }

    private static java.lang.Throwable getNestedException(java.lang.Throwable, java.lang.String, java.lang.String)
    {
        java.lang.Throwable r2, $r9;
        java.lang.Object[] r7;
        java.lang.Class[] r4;
        java.lang.Exception $r10;
        java.lang.Class $r1, $r3;
        java.lang.Object $r8;
        java.lang.String r0, r5;
        java.lang.reflect.Method $r6;
        boolean $z0;

        r2 := @parameter0: java.lang.Throwable;

        r0 := @parameter1: java.lang.String;

        r5 := @parameter2: java.lang.String;

     label1:
        $r1 = staticinvoke <java.lang.Class: java.lang.Class forName(java.lang.String)>(r0);

        $r3 = virtualinvoke r2.<java.lang.Object: java.lang.Class getClass()>();

        $z0 = virtualinvoke $r1.<java.lang.Class: boolean isAssignableFrom(java.lang.Class)>($r3);

        if $z0 == 0 goto label3;

        r4 = newarray (java.lang.Class)[0];

        $r6 = virtualinvoke $r1.<java.lang.Class: java.lang.reflect.Method getMethod(java.lang.String,java.lang.Class[])>(r5, r4);

        r7 = newarray (java.lang.Object)[0];

        $r8 = virtualinvoke $r6.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(r2, r7);

        $r9 = (java.lang.Throwable) $r8;

        return $r9;

     label2:
        $r10 := @caughtexception;

     label3:
        return null;

        catch java.lang.Exception from label1 to label2 with label2;
    }

    public java.lang.Throwable initCause(java.lang.Throwable)
    {
        java.lang.Throwable r1;
        org.jdom.JDOMException r0;

        r0 := @this: org.jdom.JDOMException;

        r1 := @parameter0: java.lang.Throwable;

        r0.<org.jdom.JDOMException: java.lang.Throwable cause> = r1;

        return r0;
    }

    public void printStackTrace()
    {
        java.lang.Throwable $r1, r3;
        java.io.PrintStream $r2;
        org.jdom.JDOMException r0;
        boolean $z0;

        r0 := @this: org.jdom.JDOMException;

        specialinvoke r0.<java.lang.Throwable: void printStackTrace()>();

        r3 = r0;

        goto label2;

     label1:
        $r2 = <java.lang.System: java.io.PrintStream err>;

        virtualinvoke $r2.<java.io.PrintStream: void print(java.lang.String)>("Caused by: ");

        virtualinvoke $r1.<java.lang.Throwable: void printStackTrace()>();

        $z0 = $r1 instanceof org.jdom.JDOMException;

        if $z0 != 0 goto label3;

        r3 = $r1;

     label2:
        $r1 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable)>(r3);

        if $r1 != null goto label1;

     label3:
        return;
    }

    public void printStackTrace(java.io.PrintStream)
    {
        java.io.PrintStream r1;
        java.lang.Throwable $r2, r3;
        org.jdom.JDOMException r0;
        boolean $z0;

        r0 := @this: org.jdom.JDOMException;

        r1 := @parameter0: java.io.PrintStream;

        specialinvoke r0.<java.lang.Throwable: void printStackTrace(java.io.PrintStream)>(r1);

        r3 = r0;

        goto label2;

     label1:
        virtualinvoke r1.<java.io.PrintStream: void print(java.lang.String)>("Caused by: ");

        virtualinvoke $r2.<java.lang.Throwable: void printStackTrace(java.io.PrintStream)>(r1);

        $z0 = $r2 instanceof org.jdom.JDOMException;

        if $z0 != 0 goto label3;

        r3 = $r2;

     label2:
        $r2 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable)>(r3);

        if $r2 != null goto label1;

     label3:
        return;
    }

    public void printStackTrace(java.io.PrintWriter)
    {
        java.io.PrintWriter r1;
        java.lang.Throwable $r2, r3;
        org.jdom.JDOMException r0;
        boolean $z0;

        r0 := @this: org.jdom.JDOMException;

        r1 := @parameter0: java.io.PrintWriter;

        specialinvoke r0.<java.lang.Throwable: void printStackTrace(java.io.PrintWriter)>(r1);

        r3 = r0;

        goto label2;

     label1:
        virtualinvoke r1.<java.io.PrintWriter: void print(java.lang.String)>("Caused by: ");

        virtualinvoke $r2.<java.lang.Throwable: void printStackTrace(java.io.PrintWriter)>(r1);

        $z0 = $r2 instanceof org.jdom.JDOMException;

        if $z0 != 0 goto label3;

        r3 = $r2;

     label2:
        $r2 = staticinvoke <org.jdom.JDOMException: java.lang.Throwable getNestedException(java.lang.Throwable)>(r3);

        if $r2 != null goto label1;

     label3:
        return;
    }

    public static void <clinit>()
    {
        <org.jdom.JDOMException: java.lang.String CVS_ID> = "@(#) $RCSfile: JDOMException.java,v $ $Revision: 1.23 $ $Date: 2004/02/27 11:32:57 $ $Name: jdom_1_0 $";

        return;
    }
}
